"""Pin the Claude Code projection contract: .claude/ mirrors .agents/.

The projection is generated by `install.sh` from the canonical `.agents/`
tree, so the expected sets here are COMPUTED from that tree rather than
frozen: what this pins is that the projection exists, matches the canonical
tree exactly, uses relative symlinks, and excludes exactly the files that
must never auto-load — whose exclusion set this module owns as the single
source of it (see `.agents/rules/README.md`'s exclusion section).
"""

from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

# The single owner of the rules-projection exclusion set. block-git-mutations.md
# is a prohibition a live PreToolUse hook enforces whether or not an agent ever
# reads it, and README.md is a table of contents, not a rule. Both stay in
# .agents/rules/ (consumers of the tree may read them directly) but are
# deliberately not projected into .claude/rules/ for ambient auto-load.
CLAUDE_RULES_EXCLUDED = {"block-git-mutations.md", "README.md"}

#: The env key that sets how deep a session's context grows before Claude Code
#: compacts it. `.claude/settings.json` is its single owner -- nothing here
#: pins a number. A number restated in this file would be a second writable
#: store of one value (`.agents/rules/single-source-of-truth.md`).
COMPACTION_WINDOW_KEY = "CLAUDE_CODE_AUTO_COMPACT_WINDOW"

_SKILL_AGENTS_DIR = re.compile(r"agents$")


def _expected_agents() -> set[str]:
    """specialists + skill-private agents (<skill>-<name>) + the architect
    workflow projected as a dispatchable agent — the same enumeration
    install.sh performs."""
    expected = {p.stem for p in (ROOT / ".agents/specialists").glob("*.md")}
    for agents_dir in (ROOT / ".agents/skills").glob("*/agents"):
        if not agents_dir.is_dir():
            continue
        skill = agents_dir.parent.name
        for agent_file in agents_dir.glob("*.md"):
            expected.add(f"{skill}-{agent_file.stem}")
    if (ROOT / ".agents/workflows/architect.md").is_file():
        expected.add("architect")
    return expected


def compaction_window_is_well_formed(value: object) -> bool:
    """Whether Claude Code can read *value* as a token count.

    The settings schema types this key as a **string** holding a decimal
    count, so an integer, a thousands separator, or an empty string is the
    dangerous shape: the setting is silently ignored and compaction stays on
    its default with nothing reporting the drift.
    """
    return isinstance(value, str) and value.isdigit() and int(value) > 0


def test_claude_md_is_a_symlink_into_agents() -> None:
    path = ROOT / "CLAUDE.md"
    assert path.is_symlink(), "CLAUDE.md must be a symlink (to AGENTS.md)"


def test_claude_projection_contains_expected_agents_and_commands() -> None:
    claude_agents = {path.stem for path in (ROOT / ".claude/agents").glob("*.md")}
    claude_commands = {path.stem for path in (ROOT / ".claude/commands").glob("*.md")}

    assert claude_agents == _expected_agents()
    assert claude_commands == {
        path.stem for path in (ROOT / ".agents/workflows").glob("*.md")
    }
    assert (ROOT / ".claude/settings.json").is_file()


def test_compaction_window_is_present_and_well_formed() -> None:
    settings = json.loads(
        (ROOT / ".claude/settings.json").read_text(encoding="utf-8")
    )
    assert COMPACTION_WINDOW_KEY in settings["env"], (
        f"{COMPACTION_WINDOW_KEY} is absent from .claude/settings.json, so "
        "auto-compaction runs on the harness default and long orchestrations "
        "lose the compaction-checkpoint protocol's headroom"
    )
    window = settings["env"][COMPACTION_WINDOW_KEY]
    assert compaction_window_is_well_formed(window), (
        f"{COMPACTION_WINDOW_KEY} is {window!r}; Claude Code reads this key as "
        "a decimal token count inside a JSON string, so any other shape is "
        "ignored silently"
    )


def test_a_malformed_compaction_window_is_rejected() -> None:
    assert compaction_window_is_well_formed("400000")
    assert not compaction_window_is_well_formed(400000)  # an int, not the schema's str
    assert not compaction_window_is_well_formed("400_000")
    assert not compaction_window_is_well_formed("0")
    assert not compaction_window_is_well_formed("")


def test_claude_rules_excluded_set_names_exist_on_disk() -> None:
    agents_rules_dir = ROOT / ".agents/rules"
    for name in CLAUDE_RULES_EXCLUDED:
        assert (agents_rules_dir / name).is_file(), (
            f"{name!r} in CLAUDE_RULES_EXCLUDED does not exist under "
            f"{agents_rules_dir} -- update or remove the stale exclusion"
        )


def test_claude_projection_rules_is_directory_of_per_file_relative_symlinks() -> None:
    agents_rules_dir = ROOT / ".agents/rules"
    claude_rules_dir = ROOT / ".claude/rules"

    assert claude_rules_dir.is_dir()
    assert not claude_rules_dir.is_symlink()

    expected_names = {
        path.name for path in agents_rules_dir.glob("*.md")
    } - CLAUDE_RULES_EXCLUDED
    actual_names = {
        path.name for path in claude_rules_dir.iterdir() if path.name != ".DS_Store"
    }
    assert actual_names == expected_names

    for name in actual_names:
        projected = claude_rules_dir / name
        assert projected.is_symlink()
        assert projected.resolve() == (agents_rules_dir / name).resolve()
        # resolve() can succeed on an absolute, machine-specific link; the
        # projection must be portable, so the on-dink link itself must be
        # relative.
        assert not projected.readlink().is_absolute(), (
            f"{projected} is an absolute symlink ({projected.readlink()}); "
            "projected rule symlinks must be relative"
        )


def test_claude_agents_are_per_file_relative_symlinks() -> None:
    claude_agents_dir = ROOT / ".claude/agents"
    assert claude_agents_dir.is_dir()
    for path in claude_agents_dir.glob("*.md"):
        assert path.is_symlink(), f"{path} must be a symlink"
        assert path.resolve().is_file(), f"{path} resolves to nothing"
        assert not path.readlink().is_absolute(), (
            f"{path} is an absolute symlink; projected agent links must be relative"
        )


def test_claude_skills_is_symlink_to_agents_skills() -> None:
    claude_skills_dir = ROOT / ".claude/skills"
    assert claude_skills_dir.is_symlink()
    assert claude_skills_dir.resolve() == (ROOT / ".agents/skills").resolve()
